# Generated by Django 5.0.3 on 2024-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='creator',
            field=models.CharField(max_length=256),
        ),
    ]
