# Generated by Django 5.0.3 on 2024-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='file_model',
            field=models.FileField(default='/static/img/default.gltf', upload_to='models'),
        ),
        migrations.AddField(
            model_name='work',
            name='file_textures',
            field=models.FileField(null=True, upload_to='models/textures'),
        ),
    ]
