# Generated by Django 5.0.3 on 2024-03-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='teacher',
            field=models.IntegerField(default=0),
        ),
    ]
