# Generated by Django 5.0.3 on 2024-03-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_mark_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='teacher',
            field=models.CharField(max_length=256),
        ),
    ]
