# Generated by Django 5.0.3 on 2024-03-21 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_alter_mark_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classrooms.work'),
        ),
    ]
