# Generated by Django 5.0.3 on 2024-03-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель')], default='student', max_length=20),
        ),
    ]
